\documentclass[final]{beamer}
\usepackage{graphicx}
\usepackage{color}
\usepackage{amsmath}
\usepackage{epstopdf}
\usepackage{multicol}
\usepackage{ragged2e}

%\usepackage{polski}
%% maxwidth is the original width if it is less than linewidth
%% otherwise use linewidth (to make sure the graphics do not exceed the margin)
\makeatletter
\def\maxwidth{ %
  \ifdim\Gin@nat@width>\linewidth
    \linewidth
  \else
    \Gin@nat@width
  \fi
}
\makeatother

\usepackage{framed}
\makeatletter
\newenvironment{kframe}{%
 \def\at@end@of@kframe{}%
 \ifinner\ifhmode%
  \def\at@end@of@kframe{\end{minipage}}%
  \begin{minipage}{\columnwidth}%
 \fi\fi%
 \def\FrameCommand##1{\hskip\@totalleftmargin \hskip-\fboxsep
 \colorbox{shadecolor}{##1}\hskip-\fboxsep
     % There is no \\@totalrightmargin, so:
     \hskip-\linewidth \hskip-\@totalleftmargin \hskip\columnwidth}%
 \MakeFramed {\advance\hsize-\width
   \@totalleftmargin\z@ \linewidth\hsize
   \@setminipage}}%
 {\par\unskip\endMakeFramed%
 \at@end@of@kframe}
\makeatother

\definecolor{shadecolor}{rgb}{.97, .97, .97}
\definecolor{messagecolor}{rgb}{0, 0, 0}
\definecolor{warningcolor}{rgb}{1, 0, 1}
\definecolor{errorcolor}{rgb}{1, 0, 0}
\newenvironment{knitrout}{}{} % an empty environment to be redefined in TeX

\usepackage{alltt}
\usepackage{grffile}
\mode<presentation>{\usetheme{Poster}}

\usepackage[utf8]{inputenc}
\usepackage{amsfonts}
\usepackage{amsmath}
\usepackage{natbib}
\usepackage{graphicx}
\usepackage{array,booktabs,tabularx}
\usepackage{epstopdf}
\usepackage[dvipsnames]{xcolor}
\usepackage{colortbl}
\newcolumntype{Z}{>{\centering\arraybackslash}X}

% rysunki
\usepackage{tikz}
\usepackage{ifthen}
\usepackage{xxcolor}
\usetikzlibrary{arrows}
\usetikzlibrary[topaths]
\usetikzlibrary{decorations.pathreplacing}
\usefonttheme[onlymath]{serif}
\boldmath
\usepackage[orientation=portrait,size=a0,scale=1,debug]{beamerposter}                       % e.g. for DIN-A0 poster
%\usepackage[orientation=portrait,size=a1,scale=1.4,grid,debug]{beamerposter}                  % e.g. for DIN-A1 poster, with optional grid and debug output
%\usepackage[size=custom,width=200,height=120,scale=2,debug]{beamerposter}                     % e.g. for custom size poster
%\usepackage[orientation=portrait,size=a0,scale=1.0,printer=rwth-glossy-uv.df]{beamerposter}   % e.g. for DIN-A0 poster with rwth-glossy-uv printer check
% ...
%

\setbeamertemplate{caption}[numbered]

%!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

\newlength{\columnheight}
\setlength{\columnheight}{89cm} % ------------------------------- od jakiej wysokości mają zaczynać się klocki, ale też miejsce dla tytułu autorów, afiliacji
\renewcommand{\thetable}{}
\def\andname{,}
\authornote{}



\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\begin{document}


% Początek posteru
%-------------------------------------------------------------------------------------------------------------------
%--------------------------------------------------------------Tytuł
\title{\huge \textbf{HaDeX}: an R package and web-server for analysis of data from hydrogen deuterium exchange - mass spectrometry experiments} 

% -----------------------------------------------------------Autorzy, mail, afiliacje
\date{}
\author{Weronika Pucha\l{}a\,$^{\text{\sfb 1}}$,
Micha\l{} Burdukiewicz\,$^{\text{\sfb 2}}$,
Micha\l{} Kistowski\,$^{\text{\sfb 1}}$,
Katarzyna D\k{a}browa-D\k{a}browska\,$^{\text{\sfb 1}}$,
Aleksandra E. Badaczewska-Dawid\,$^{\text{\sfb 3}}$,\\ 
Dominik Cysewski\,$^{\text{\sfb 1},*}$,
Micha\l{} Dadlez\,$^{\text{\sfb 1}}$\\
\normaltext{*dominikcysewski@gmail.com}}
\institute{$^{\text{\sf 1}}$Institute of Biochemistry and Biophysics Polish Academy of Sciences, Poland,
$^{\text{\sf 2}}$Faculty of Mathematics and Information Science, Warsaw University of 
Technology, Poland,
$^{\text{\sf 3}}$Faculty of Chemistry, Biological and Chemical Research Center, University of Warsaw, Poland.
}
}

 \begin{frame}
 
\begin{columns}
\begin{column}{.5\textwidth} %------------------------------------------------ szerokość kolumny lewej
\begin{beamercolorbox}[center,wd=\textwidth]{postercolumn}
\begin{minipage}[T]{.99\textwidth}
\parbox[t][\columnheight]{\textwidth}
{

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{block}{Introduction}
<<echo=FALSE, warning=FALSE, error=FALSE, message=FALSE>>=
library(HaDeX)
library(ggplot2)
#library(patchwork)
library(dplyr)

knitr::opts_chunk$set(out.width=1000, out.height=750)

poster_theme <- theme_bw(base_size = 10) +
                theme(legend.position = "bottom",
                      legend.title = element_blank())

dat <- read_hdx(system.file(package = "HaDeX", "HaDeX/data/KD_190304_Nucb2_EDTA_CaCl2_test02_clusterdata.csv"))

calc_dat <- prepare_dataset(dat,
                             in_state_first = "gg_Nucb2_EDTA_0.001",
                             chosen_state_first = "gg_Nucb2_EDTA_25",
                             out_state_first = "gg_Nucb2_EDTA_1440",
                             in_state_second = "gg_Nucb2_CaCl2_0.001",
                             chosen_state_second = "gg_Nucb2_CaCl2_25",
                             out_state_second = "gg_Nucb2_CaCl2_1440") 

@

\justify Hydrogen-deuterium mass spectrometry (HDX-MS) is a staple tool for monitoring dynamics and interactions of proteins. Due to the sheer size of the HDX-MS results, the data analysis require a dedicated software suite. However, the majority of existing tools provides only point-and-click interfaces to black-box models or does not offer a complete workflow. We propose \textbf{HaDeX}, a novel tool for processing, analysis and visualisation of HDX-MS experiments. \textbf{HaDeX} covers the whole analytic process, including preliminary data exploration, quality control and generation of publication-quality figures. The reproducibility of the whole procedure is ensured with advanced reporting functions.

\end{block}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{block}{Coverage of the sequence} 

\justify The \textbf{HaDeX} web server relies only on a single data format: DynamiX datafile. An user can customize each step of the analysis with his own input parameters.

We start our analysis with summary of protein coverage (as shown below). It is provided in two forms, histogram and graphic comparison of positions. Also the reconstruction of the sequence is available - based on experimental data.

\begin{figure}
\includegraphics[width=0.95\columnwidth]{app_coverage.pdf}
\caption{Sequence coverage analysis (\textbf{HaDeX} web server).}
\end{figure}

\end{block}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{block}{Differential plot}

\justify An important aspect of analysing data is a comparison of peptide deuteration in different states. A relative deuteration level used by \textbf{HaDeX} is defined by the equation \ref{eq:deut_lev}.

\begin{equation}
D = \frac{D_{t} - D_{0}}{D_{100} - D_{0}}
\label{eq:deut_lev}
\end{equation}

\justify The equation \ref{eq:deut_lev} is a function of three variables (each with its own uncertainty), so there is need to use the Law of Propagation of Uncertainty, defined in equation \ref{eq:law_un}

\begin{equation}
u_{c}(y) = \sqrt{\sum_{k} \left[ \frac{\partial y}{\partial x_{k}} u(x_{k}) \right]^2}
\label{eq:law_un}
\end{equation}

\justify Applying equation \ref{eq:law_un} to equation \ref{eq:deut_lev}, we get deuteration level uncertainty described by equation \ref{eq:deut_lev_un}

\begin{equation}
u_{c}(D) = \sqrt{ \left[ \frac{1}{D_{100}-D_{0}} u(D_{t}) \right]^2 + \left[ \frac{D_{t} - D_{100}}{(D_{100}-D_{0})^2} u(D_{0}) \right]^2 + \left[ \frac{D_{0} - D_{t}}{(D_{100}-D_{0})^2} u(D_{100}) \right]^2}
\label{eq:deut_lev_un}
\end{equation}

\justify The levels of deuteration along with uncertainty intervals are shown on comparison plot~\ref{fig:comp_plots}. \textbf{HaDeX} provide both experimental and theroetical levels of deuteration.
\begin{figure}
<<echo=FALSE, warning=FALSE, message=FALSE, error=FALSE, fig.align="center">>=

 c1 <- comparison_plot(calc_dat = calc_dat,
                 # plot_title = "Theoretical fraction exchanged in \nstate comparison in 25 min time",
                 theoretical = TRUE,
                 state_first = "Nucb2 Factor 1",
                 state_second = "Nucb2 Factor 2") +
   poster_theme 

 c2 <- comparison_plot(calc_dat = calc_dat,
                 # plot_title = "Fraction exchanged in state comparison \nin 25 min time",
                 theoretical = FALSE,
                 state_first = "Nucb2 Factor 1",
                 state_second = "Nucb2 Factor 2") +
   poster_theme
 
 c1 # + c2
 
 @
\caption{Comparison plots - comparing experimental and theoretical calculations, based on example data.}
\label{fig:comp_plots}
\end{figure}

\end{block}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{block}{Availability}

     \url{http://mslab-ibb.pl/shiny/HaDeX/}$\begin{array}{l}
        \begin{figure}[ht]
        \centering
        \scalebox{0.025}{
          \includegraphics{hadex_qr.eps}
        }
        \end{figure}
      \end{array}

HaDeX is also available as the R package:
<<echo=TRUE, eval=FALSE, warning=FALSE, message=FALSE, error=FALSE, fig.align="center">>=
source("https://install-github.me/michbur/HaDeX")
@



\end{block}

}
\end{minipage}
\end{beamercolorbox}
\end{column}


%new column -------------------------------------------------------------------------------------------------    

\begin{column}{.47\textwidth} % ----------------------------------------- szerokość kolumny prawej
\begin{beamercolorbox}[center,wd=\textwidth]{postercolumn}
\begin{minipage}[T]{.99\textwidth}  
\parbox[t][\columnheight]{\textwidth}
{

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{block}{Woods plot format}

\justify Woods plot format shows diference between results of two different states as described by equation \ref{eq:diff}.

\begin{equation}
diff = D_{1} - D_{2}
\label{eq:diff}
\end{equation}

Equation \ref{eq:diff} is a function of two variables, so applying \ref{eq:law_un} we get uncertainty described by equation \ref{eq:diff_un}.

\begin{equation}
u_{c}(diff) = \sqrt{u(D_{1})^2 + u(D_{2})^2}
\label{eq:diff_un}
\end{equation}

\justify Described calculations lead to results shown on Woods plot format - figure \ref{fig:woods_plots} below.

\begin{figure}
<<echo=FALSE, warning=FALSE, error=FALSE, message=FALSE, fig.align="center">>=

 w1 <- woods_plot(calc_dat = calc_dat,
            # plot_title = "Theoretical fraction exchanged between \nstates in 25 min time",
            theoretical = TRUE) +
   poster_theme +
   scale_y_continuous(limits = c(-0.6, 0.8), expand = c(0, 0))
 
 w2 <- woods_plot(calc_dat = calc_dat,
            # plot_title = "Fraction exchanged between states \nin 25 min time",
            theoretical = FALSE) +
   poster_theme +
   scale_y_continuous(limits = c(-0.6, 0.8), expand = c(0, 0))
 
 w1 # + w2
 
@
\caption{Plots in Woods format - comparing experimental and theoretical calculations, based on example data.}
\label{fig:woods_plots}
\end{figure}

\end{block}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{block}{Quality control}

\justify \textbf{HaDeX} provides additional tools for assement of experiments. For example, the quality control function shows
how the mean uncertainty per peptide changes with time points of an experiment.

\begin{figure}
<<echo=FALSE, message=FALSE, warning=FALSE, error=FALSE, fig.align="center", fig.height=3.5, fig.width=6,out.height=450>>=
 
 result <- quality_control(dat = dat,
                          state_first = "gg_Nucb2_EDTA",
                          state_second = "gg_Nucb2_CaCl2", 
                          chosen_time = 25, 
                          in_time = 0.001)

 ggplot(result[result["time"]>=1,]) + 
  geom_line(aes(x = time, y = avg_err_state_first, color = "Average error (first state)")) +
  geom_line(aes(x = time, y = avg_err_state_second, color = "Average error (second state)")) +
  scale_x_log10() +
  labs(x = "log(time) [min]", y = "Average uncertainty", title = "Uncertainty change") + 
  theme_bw(base_size = 11) +
  theme(legend.position = "bottom",
        legend.title = element_blank())

@
\caption{Plot ilustrating uncertainy change depending on used out parameter}
\end{figure}

\end{block}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{block}{Report function}

\begin{columns}
\begin{column}{0.5\textwidth}
   \textbf{HaDeX} provides report generation - with parameters chosen by user so is fully personalizable. Additionaly, calculated data for plots can be downloaded not only in report form but also in csv/pdf file in panel next to every plot. On figure \ref{fig:rep} are shown available elements of the report - that can be chosen by user and limited strickly for user needs.
\end{column}
\begin{column}{0.5\textwidth}  %%<--- here
    \begin{center}
     \begin{figure}
\includegraphics[width=0.9\columnwidth]{app_report.png}
\caption{Screenshot of \textbf{HaDeX} - reporting page}
\label{fig:rep}
\end{figure}
     \end{center}
\end{column}
\end{columns}

\end{block}



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{block}{Acknowledgements}

\justify The project is carried out within the TEAM TECH programme of the Foundation for Polish Science co-financed by the European Union under the European Regional Development Fund.(TEAM TECH CORE FACILITY/2016-2/2) „Mass Spectrometry of Biopharmaceuticals-improved methodologies for qualitative, quantitative and structural characterization of drugs, proteinaceous drug targets and diagnostic molecules”

\begin{figure}
\includegraphics[width=0.95\columnwidth]{figure/listwa.png}
\end{figure}

\end{block}

\begin{block}{Bibliography}


\begin{enumerate}
\small
\item [1] Start2Fold: a database of hydrogen/deuterium exchange data on protein folding and stability. Pancsa R,
Varadi M, Tompa P, Vranken WF. Nucleic Acids Res. 2016 Jan 4;44(D1):D429-34. doi:
10.1093/nar/gkv1185. Epub 2015 Nov 17
\item [2] HDX workbench: software for the analysis of H/D exchange MS data. Pascal BD, Willis S, Lauer JL,
Landgraf RR, West GM, Marciano D, Novick S, Goswami D, Chalmers MJ, Griffin PR. J Am Soc Mass
Spectrom. 2012 Sep;23(9):1512-21. doi: 10.1007/s13361-012-0419-6. Epub 2012 Jun 13.
\item [3] MEMHDX: an interactive tool to expedite the statistical validation and visualization of large HDX-MS
datasets. Hourdel V, Volant S, O'Brien DP, Chenal A, Chamot-Rooke J, Dillies MA, Brier S. Bioinformatics.
2016 Nov 15;32(22):3413-3419. Epub 2016 Jul 13
\item [4] Deuteros: software for rapid analysis and visualization of data from differential hydrogen deuterium exchange-mass spectrometry, Andy M C Lau, Zainab Ahdash, Chloe Martens, Argyris Politis, , Bioinformatics, btz022, https://doi.org/10.1093/bioinformatics/btz022
\item [5] ISO, Guide to the Expression of Uncertainty in Measurement (International Organization for Standardization, Geneva, Switzerland, 1993)
\end{enumerate}
\end{block}



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

}
\end{minipage}
\end{beamercolorbox}
\end{column}
\end{columns}  


\end{frame}


\end{document}