\documentclass{beamer}
\usetheme{focus}
\definecolor{main}{RGB}{113, 93, 145}
\definecolor{background}{RGB}{248, 241, 255}
\usepackage[utf8]{inputenc}
\usepackage{polski}
\usepackage{amsfonts}
\usepackage{amsmath}
\usepackage{natbib}
\usepackage{graphicx}
\usepackage{array,booktabs,tabularx}
\usepackage{epstopdf}
\usepackage{colortbl, xcolor}
\usepackage{url}
\usepackage{ulem}
\usepackage{animate}

\newcommand\Fontvi{\fontsize{6}{7.2}\selectfont}

\newcommand{\btVFill}{\vskip0pt plus 1filll}

\title{HaDeX: an R package and \mbox{web-server} for analysis of \mbox{data} from HDX-MS experiments}
\date{}
\author{Dominik Cysewski}
\institute{Institute of Biochemistry and Biophysics \\ Polish Academy of Sciences}

\begin{document}

<<knitrIntro, echo = FALSE, message=FALSE,warning=FALSE>>=
source("my_ggplot_theme.R")

library(dplyr)
library(reshape2)
library(xtable)
library(biogram)
library(seqinr)


@


\maketitle

\begin{frame}{HDX-MS}

\begin{figure} 
\includegraphics[width=0.80\textwidth]{static_figure/HDX-2.pdf}
\end{figure}

The longer incubation time, the more protected hydrogens are being replaced by deuters.

\end{frame}

% \begin{frame}{Applications}
% 
% \begin{figure} 
% \includegraphics[width=0.85\textwidth]{static_figure/hdx-applications.png}
% \end{figure}
% 
% 
% \tiny G. R. Masson et. al. (2019).
% Recommendations for performing, interpreting and reporting
% hydrogen deuterium exchange mass spectrometry (HDX-MS)
% experiments. Nature Methods, 16(7):595–602..
% 
% \end{frame}

\begin{frame}{Multi-state analysis}

<<echo=FALSE,fig.height=4>>=
dat <- read.csv("./data/example_peptide.csv")

plot_dat <- select(dat, frac_exch_state_1, frac_exch_state_2, state) %>% 
  mutate(time = as.numeric(sapply(strsplit(as.character(state), "_"), last))) %>% 
  select(-state) %>% 
  melt(id.vars = "time") %>% 
  mutate(variable = ifelse(variable == "frac_exch_state_1", "State a", "State b")) 

ggplot(plot_dat, aes(x = time, y = value, color = variable)) +
  geom_point(size = 4) +
  geom_line(linetype = "dashed", size = 1) +
  scale_y_continuous("Relative deuteration") +
  scale_x_continuous("Time [s]") +
  scale_color_discrete("") +
  ggtitle(plot_dat[1, "Sequence"]) +
  my_theme

@


Peptides may come from proteins in differents states, i.e. bounded by different cofactors.

\end{frame}


\begin{frame}

\begin{center}
  \animategraphics[autoplay,loop,width=0.65\linewidth]{15}{static_figure/animation/gganim_plot}{0001}{0100}
\end{center}

During the analysis of the HDX-MS data we have to consider both time of the incubation and position of a peptide in a sequence. 
\end{frame}


\begin{frame}{Relative deuteration}
\begin{figure} 
\includegraphics[width=\textwidth]{static_figure/HaDeX-2.png}
\end{figure}
\end{frame}

% \begin{frame}{Peptide coverage}
% \begin{figure} 
% \includegraphics[width=\textwidth]{static_figure/HaDeX-4.png}
% \end{figure}
% \end{frame}


\begin{frame}{Deuteration kinetics}
\begin{figure} 
\includegraphics[width=\textwidth]{static_figure/HaDeX-6.png}
\end{figure}
\end{frame}


\begin{frame}{Reporting}
\begin{figure} 
\includegraphics[width=0.8\textwidth]{static_figure/HaDeX-7.png}
\end{figure}

\begin{figure} 
\includegraphics[width=0.8\textwidth]{static_figure/HaDeX-8.png}
\end{figure}
\end{frame}

\begin{frame}{Summary and availability}

Summary:

\begin{itemize}
\item rapidly developing technologies require a flexible framework,
\item the methods of data analysis should follow the development of both technology and expectations of its users.
\end{itemize}

\medskip

Availability:

\begin{itemize}
\item a web-server (\url{http://mslab-ibb.pl/shiny/HaDeX/}), 
\item the R package (\url{https://CRAN.R-project.org/package=HaDeX}),
\item a standalone software (\url{https://sourceforge.net/projects/HaDeX/}).
\end{itemize}
\end{frame} 



\begin{frame}{Acknowledgements}


\begin{columns}
\begin{column}{0.5\textwidth}
   \begin{itemize}
   \item Mass Spectrometry Lab, Institute of Biochemistry and Biophysics, PAS.
   \item MI$^2$ Data Lab, Faculty of Mathematics and Information Science, Warsaw University of Technology.
   \end{itemize}
\end{column}
\begin{column}{0.5\textwidth}  %%<--- here
    \begin{center}
    \includegraphics[width=0.9\textwidth]{static_figure/ibb_logo.png}
     \includegraphics[width=0.9\textwidth]{static_figure/mi2.png}
     \end{center}
\end{column}
\end{columns}

\medskip 

\small Funding: Foundation of Polish Science TEAM TECH CORE FACILITY/2016-2/2 Mass Spectrometry of Biopharmaceuticals - improved methodologies for qualitative, quantitative and structural characterization of drugs, proteinaceous drug targets and diagnostic molecules.

\end{frame}

\begin{frame}{Acknowledgements}

\begin{columns}
\begin{column}{0.4\textwidth}
HaDeX developers:
  \begin{itemize}
    \item Weronika Puchala (main developer),
    \item Dominik Rafacz (frontend developer),
    \item Michał Burdukiewicz.
  \end{itemize}
\end{column}
\begin{column}{0.6\textwidth}  %%<--- here
  \begin{center}
    \includegraphics[width=0.35\textwidth]{static_figure/weronika.png}
    \\
    \includegraphics[width=0.35\textwidth]{static_figure/dominik.png}
    \\
    \includegraphics[width=0.35\textwidth,height=0.35\textwidth]{static_figure/michal.jpg}
  \end{center}
\end{column}
\end{columns}
\end{frame} 

\end{document}